version: 2

# Adapted from https://github.com/circleci/circleci-docs/blob/master/.circleci/config.yml
# I'd love to find docs on this syntax.
references:
  js_deps_paths: &js_deps_paths
  - node_modules/
  - .docz/node_modules
  build_cache_paths: &build_cache_paths
  - public/
  js_deps_cache_key: &js_deps_cache_key
    js-deps-v{{.Environment.CACHE_VERSION}}-{{checksum "yarn.lock"}}
  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/project

workflows:
  version: 2
  build_deploy:
    jobs:
    - build
    - upload_docs:
        requires:
          - build
jobs:
  build:
    docker:
    - image: circleci/node:8.15
    steps:
    - checkout
    - persist_to_workspace:
        root: ~/project
        paths:
          - "*"
    - restore_cache:
        keys:
        - *js_deps_cache_key
    - run:
        name: Conditional install
        command: if [ ! -d node_modules ]; then yarn install --frozen-lockfile; fi
    - save_cache:
        paths: *js_deps_paths
        key: *js_deps_cache_key
    - run:
        name: Build Site
        command: yarn build
    - persist_to_workspace:
        root: ~/project
        paths: *build_cache_paths
  upload_docs:
    docker:
    - image: circleci/node:8.15
    steps:
    - *attach_workspace
    - run:
        name: Upload docs to surge.sh
        command: .circleci/upload-docs.sh
